// GENERATED by scripts/process-screenshots.mjs from scripts/shots.config.mjs — do not edit.
import s0_avif_2880 from "@/assets/screenshots/desktop/overview-2880.avif";
import s0_avif_1440 from "@/assets/screenshots/desktop/overview-1440.avif";
import s0_webp_1440 from "@/assets/screenshots/desktop/overview-1440.webp";
import s0_jpg_1440 from "@/assets/screenshots/desktop/overview-1440.jpg";
import s1_avif_2880 from "@/assets/screenshots/desktop/now-playing-2880.avif";
import s1_avif_1440 from "@/assets/screenshots/desktop/now-playing-1440.avif";
import s1_webp_1440 from "@/assets/screenshots/desktop/now-playing-1440.webp";
import s1_jpg_1440 from "@/assets/screenshots/desktop/now-playing-1440.jpg";
import s2_avif_2880 from "@/assets/screenshots/desktop/anime-grid-2880.avif";
import s2_avif_1440 from "@/assets/screenshots/desktop/anime-grid-1440.avif";
import s2_webp_1440 from "@/assets/screenshots/desktop/anime-grid-1440.webp";
import s2_jpg_1440 from "@/assets/screenshots/desktop/anime-grid-1440.jpg";
import s3_avif_2880 from "@/assets/screenshots/desktop/anime-rows-2880.avif";
import s3_avif_1440 from "@/assets/screenshots/desktop/anime-rows-1440.avif";
import s3_webp_1440 from "@/assets/screenshots/desktop/anime-rows-1440.webp";
import s3_jpg_1440 from "@/assets/screenshots/desktop/anime-rows-1440.jpg";
import s4_avif_2880 from "@/assets/screenshots/desktop/manga-grid-2880.avif";
import s4_avif_1440 from "@/assets/screenshots/desktop/manga-grid-1440.avif";
import s4_webp_1440 from "@/assets/screenshots/desktop/manga-grid-1440.webp";
import s4_jpg_1440 from "@/assets/screenshots/desktop/manga-grid-1440.jpg";
import s5_avif_2880 from "@/assets/screenshots/desktop/library-2880.avif";
import s5_avif_1440 from "@/assets/screenshots/desktop/library-1440.avif";
import s5_webp_1440 from "@/assets/screenshots/desktop/library-1440.webp";
import s5_jpg_1440 from "@/assets/screenshots/desktop/library-1440.jpg";
import s6_avif_2880 from "@/assets/screenshots/desktop/stats-overview-2880.avif";
import s6_avif_1440 from "@/assets/screenshots/desktop/stats-overview-1440.avif";
import s6_webp_1440 from "@/assets/screenshots/desktop/stats-overview-1440.webp";
import s6_jpg_1440 from "@/assets/screenshots/desktop/stats-overview-1440.jpg";
import s7_avif_2880 from "@/assets/screenshots/desktop/stats-genres-2880.avif";
import s7_avif_1440 from "@/assets/screenshots/desktop/stats-genres-1440.avif";
import s7_webp_1440 from "@/assets/screenshots/desktop/stats-genres-1440.webp";
import s7_jpg_1440 from "@/assets/screenshots/desktop/stats-genres-1440.jpg";
import s8_avif_2880 from "@/assets/screenshots/desktop/wrapped-2880.avif";
import s8_avif_1440 from "@/assets/screenshots/desktop/wrapped-1440.avif";
import s8_webp_1440 from "@/assets/screenshots/desktop/wrapped-1440.webp";
import s8_jpg_1440 from "@/assets/screenshots/desktop/wrapped-1440.jpg";
import s9_avif_2880 from "@/assets/screenshots/desktop/seasonal-2880.avif";
import s9_avif_1440 from "@/assets/screenshots/desktop/seasonal-1440.avif";
import s9_webp_1440 from "@/assets/screenshots/desktop/seasonal-1440.webp";
import s9_jpg_1440 from "@/assets/screenshots/desktop/seasonal-1440.jpg";
import s10_avif_2880 from "@/assets/screenshots/desktop/calendar-2880.avif";
import s10_avif_1440 from "@/assets/screenshots/desktop/calendar-1440.avif";
import s10_webp_1440 from "@/assets/screenshots/desktop/calendar-1440.webp";
import s10_jpg_1440 from "@/assets/screenshots/desktop/calendar-1440.jpg";
import s11_avif_2880 from "@/assets/screenshots/desktop/franchise-2880.avif";
import s11_avif_1440 from "@/assets/screenshots/desktop/franchise-1440.avif";
import s11_webp_1440 from "@/assets/screenshots/desktop/franchise-1440.webp";
import s11_jpg_1440 from "@/assets/screenshots/desktop/franchise-1440.jpg";
import s12_avif_2880 from "@/assets/screenshots/desktop/bell-2880.avif";
import s12_avif_1440 from "@/assets/screenshots/desktop/bell-1440.avif";
import s12_webp_1440 from "@/assets/screenshots/desktop/bell-1440.webp";
import s12_jpg_1440 from "@/assets/screenshots/desktop/bell-1440.jpg";
import s13_avif_2880 from "@/assets/screenshots/desktop/palette-2880.avif";
import s13_avif_1440 from "@/assets/screenshots/desktop/palette-1440.avif";
import s13_webp_1440 from "@/assets/screenshots/desktop/palette-1440.webp";
import s13_jpg_1440 from "@/assets/screenshots/desktop/palette-1440.jpg";
import s14_avif_2880 from "@/assets/screenshots/desktop/settings-detection-2880.avif";
import s14_avif_1440 from "@/assets/screenshots/desktop/settings-detection-1440.avif";
import s14_webp_1440 from "@/assets/screenshots/desktop/settings-detection-1440.webp";
import s14_jpg_1440 from "@/assets/screenshots/desktop/settings-detection-1440.jpg";
import s15_avif_2880 from "@/assets/screenshots/desktop/light-anime-grid-2880.avif";
import s15_avif_1440 from "@/assets/screenshots/desktop/light-anime-grid-1440.avif";
import s15_webp_1440 from "@/assets/screenshots/desktop/light-anime-grid-1440.webp";
import s15_jpg_1440 from "@/assets/screenshots/desktop/light-anime-grid-1440.jpg";
import s16_avif_2880 from "@/assets/screenshots/desktop/about-2880.avif";
import s16_avif_1440 from "@/assets/screenshots/desktop/about-1440.avif";
import s16_webp_1440 from "@/assets/screenshots/desktop/about-1440.webp";
import s16_jpg_1440 from "@/assets/screenshots/desktop/about-1440.jpg";
import s17_avif_1216 from "@/assets/screenshots/phone/phone-overview-1216.avif";
import s17_avif_608 from "@/assets/screenshots/phone/phone-overview-608.avif";
import s17_webp_608 from "@/assets/screenshots/phone/phone-overview-608.webp";
import s17_jpg_608 from "@/assets/screenshots/phone/phone-overview-608.jpg";
import s18_avif_1216 from "@/assets/screenshots/phone/phone-list-1216.avif";
import s18_avif_608 from "@/assets/screenshots/phone/phone-list-608.avif";
import s18_webp_608 from "@/assets/screenshots/phone/phone-list-608.webp";
import s18_jpg_608 from "@/assets/screenshots/phone/phone-list-608.jpg";
import s19_avif_1216 from "@/assets/screenshots/phone/phone-detail-1216.avif";
import s19_avif_608 from "@/assets/screenshots/phone/phone-detail-608.avif";
import s19_webp_608 from "@/assets/screenshots/phone/phone-detail-608.webp";
import s19_jpg_608 from "@/assets/screenshots/phone/phone-detail-608.jpg";
import s20_avif_1216 from "@/assets/screenshots/phone/phone-search-1216.avif";
import s20_avif_608 from "@/assets/screenshots/phone/phone-search-608.avif";
import s20_webp_608 from "@/assets/screenshots/phone/phone-search-608.webp";
import s20_jpg_608 from "@/assets/screenshots/phone/phone-search-608.jpg";
import s21_avif_1216 from "@/assets/screenshots/phone/phone-more-1216.avif";
import s21_avif_608 from "@/assets/screenshots/phone/phone-more-608.avif";
import s21_webp_608 from "@/assets/screenshots/phone/phone-more-608.webp";
import s21_jpg_608 from "@/assets/screenshots/phone/phone-more-608.jpg";

export interface Source {
  w: number;
  src: string;
}

export interface Shot {
  id: string;
  kind: "desktop" | "phone";
  /** Intrinsic size of the largest variant; the <img> carries it so nothing shifts. */
  width: number;
  height: number;
  /** One present-tense sentence naming the screen and what is on it. */
  alt: string;
  caption: string;
  avif: Source[];
  webp: Source[];
  /** The fallback the <img> itself names, at 1x. */
  jpg: Source[];
}

export const SHOTS: Shot[] = [
  {
    id: "overview",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The Overview shows this season's most popular title in a banner, four statistics tiles, the titles to continue watching and the ones airing soon.",
    caption: "Overview — the season, your numbers, what to watch next",
    avif: [{ w: 2880, src: s0_avif_2880 }, { w: 1440, src: s0_avif_1440 }],
    webp: [{ w: 1440, src: s0_webp_1440 }],
    jpg: [{ w: 1440, src: s0_jpg_1440 }],
  },
  {
    id: "now-playing",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The Now Playing window floating over the Overview: the cover of Katanagatari, episode 3 playing in mpv, the progress update counting down, and the update, skip and fix-match buttons in its header.",
    caption: "Now Playing — the floating window, an episode detected in mpv",
    avif: [{ w: 2880, src: s1_avif_2880 }, { w: 1440, src: s1_avif_1440 }],
    webp: [{ w: 1440, src: s1_webp_1440 }],
    jpg: [{ w: 1440, src: s1_jpg_1440 }],
  },
  {
    id: "anime-grid",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The anime list as a cover grid, with status tabs, a search field, sort, filters and presets above it.",
    caption: "Anime list, grid view",
    avif: [{ w: 2880, src: s2_avif_2880 }, { w: 1440, src: s2_avif_1440 }],
    webp: [{ w: 1440, src: s2_webp_1440 }],
    jpg: [{ w: 1440, src: s2_jpg_1440 }],
  },
  {
    id: "anime-rows",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The anime list as rows: cover, title, status, score and episode count editable in place, rewatches and dates beside them.",
    caption: "Anime list, rows — status, score and progress edited in place",
    avif: [{ w: 2880, src: s3_avif_2880 }, { w: 1440, src: s3_avif_1440 }],
    webp: [{ w: 1440, src: s3_webp_1440 }],
    jpg: [{ w: 1440, src: s3_jpg_1440 }],
  },
  {
    id: "manga-grid",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The manga list as a cover grid.",
    caption: "Manga list, grid view",
    avif: [{ w: 2880, src: s4_avif_2880 }, { w: 1440, src: s4_avif_1440 }],
    webp: [{ w: 1440, src: s4_webp_1440 }],
    jpg: [{ w: 1440, src: s4_jpg_1440 }],
  },
  {
    id: "library",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The local library lists three matched titles with their next unwatched file, the match confidence and a Play button each.",
    caption: "Local library — files matched to your list, next episode first",
    avif: [{ w: 2880, src: s5_avif_2880 }, { w: 1440, src: s5_avif_1440 }],
    webp: [{ w: 1440, src: s5_webp_1440 }],
    jpg: [{ w: 1440, src: s5_jpg_1440 }],
  },
  {
    id: "stats-overview",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The Statistics page's overview tab: the list's totals, then its statuses, formats and episode lengths as bars and a ring.",
    caption: "Statistics — overview",
    avif: [{ w: 2880, src: s6_avif_2880 }, { w: 1440, src: s6_avif_1440 }],
    webp: [{ w: 1440, src: s6_webp_1440 }],
    jpg: [{ w: 1440, src: s6_jpg_1440 }],
  },
  {
    id: "stats-genres",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The Statistics page's genres and tags tab: a radar of the six biggest genres, each genre's mean score against the overall one, and the tags as a treemap.",
    caption: "Statistics — genres and tags",
    avif: [{ w: 2880, src: s7_avif_2880 }, { w: 1440, src: s7_avif_1440 }],
    webp: [{ w: 1440, src: s7_webp_1440 }],
    jpg: [{ w: 1440, src: s7_jpg_1440 }],
  },
  {
    id: "wrapped",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The year-in-review page: the shape, format and size choices above the 2026 poster with the year's numbers, top genres and top-rated titles.",
    caption: "Year in review",
    avif: [{ w: 2880, src: s8_avif_2880 }, { w: 1440, src: s8_avif_1440 }],
    webp: [{ w: 1440, src: s8_webp_1440 }],
    jpg: [{ w: 1440, src: s8_jpg_1440 }],
  },
  {
    id: "seasonal",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The Seasonal page shows one season's titles in a grid, with the season switcher above it.",
    caption: "Seasonal",
    avif: [{ w: 2880, src: s9_avif_2880 }, { w: 1440, src: s9_avif_1440 }],
    webp: [{ w: 1440, src: s9_webp_1440 }],
    jpg: [{ w: 1440, src: s9_jpg_1440 }],
  },
  {
    id: "calendar",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The Calendar page shows the week's airing episodes on a Monday-first grid.",
    caption: "Calendar",
    avif: [{ w: 2880, src: s10_avif_2880 }, { w: 1440, src: s10_avif_1440 }],
    webp: [{ w: 1440, src: s10_webp_1440 }],
    jpg: [{ w: 1440, src: s10_jpg_1440 }],
  },
  {
    id: "franchise",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The franchise graph of the Monogatari series, its related titles in columns connected by lines, with Bakemonogatari's card open at the side.",
    caption: "Franchise graph",
    avif: [{ w: 2880, src: s11_avif_2880 }, { w: 1440, src: s11_avif_1440 }],
    webp: [{ w: 1440, src: s11_webp_1440 }],
    jpg: [{ w: 1440, src: s11_jpg_1440 }],
  },
  {
    id: "bell",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The notification bell open over the Overview, listing recent notifications.",
    caption: "The bell — Karasu's and AniList's notifications in one stream",
    avif: [{ w: 2880, src: s12_avif_2880 }, { w: 1440, src: s12_avif_1440 }],
    webp: [{ w: 1440, src: s12_webp_1440 }],
    jpg: [{ w: 1440, src: s12_jpg_1440 }],
  },
  {
    id: "palette",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The command palette open over the Overview, listing the titles on the list that match “mono”.",
    caption: "Command palette (Ctrl+K)",
    avif: [{ w: 2880, src: s13_avif_2880 }, { w: 1440, src: s13_avif_1440 }],
    webp: [{ w: 1440, src: s13_webp_1440 }],
    jpg: [{ w: 1440, src: s13_jpg_1440 }],
  },
  {
    id: "settings-detection",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The Detection settings pane: automatic tracking, the confirmation toggle, the threshold, media sessions and mpv.",
    caption: "Settings — detection",
    avif: [{ w: 2880, src: s14_avif_2880 }, { w: 1440, src: s14_avif_1440 }],
    webp: [{ w: 1440, src: s14_webp_1440 }],
    jpg: [{ w: 1440, src: s14_jpg_1440 }],
  },
  {
    id: "light-anime-grid",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The anime list in the light theme.",
    caption: "Light theme",
    avif: [{ w: 2880, src: s15_avif_2880 }, { w: 1440, src: s15_avif_1440 }],
    webp: [{ w: 1440, src: s15_webp_1440 }],
    jpg: [{ w: 1440, src: s15_jpg_1440 }],
  },
  {
    id: "about",
    kind: "desktop",
    width: 2880,
    height: 1800,
    alt: "The About page with the mark, the update check and the diagnostics report.",
    caption: "About",
    avif: [{ w: 2880, src: s16_avif_2880 }, { w: 1440, src: s16_avif_1440 }],
    webp: [{ w: 1440, src: s16_webp_1440 }],
    jpg: [{ w: 1440, src: s16_jpg_1440 }],
  },
  {
    id: "phone-overview",
    kind: "phone",
    width: 1216,
    height: 2581,
    alt: "The phone's Overview: this season's most popular title, four statistics tiles and the titles to continue watching, above the bottom bar.",
    caption: "Android — overview",
    avif: [{ w: 1216, src: s17_avif_1216 }, { w: 608, src: s17_avif_608 }],
    webp: [{ w: 608, src: s17_webp_608 }],
    jpg: [{ w: 608, src: s17_jpg_608 }],
  },
  {
    id: "phone-list",
    kind: "phone",
    width: 1216,
    height: 2581,
    alt: "The anime list on the phone as a four-column cover grid with the status tabs above.",
    caption: "Android — anime list",
    avif: [{ w: 1216, src: s18_avif_1216 }, { w: 608, src: s18_avif_608 }],
    webp: [{ w: 608, src: s18_webp_608 }],
    jpg: [{ w: 608, src: s18_jpg_608 }],
  },
  {
    id: "phone-detail",
    kind: "phone",
    width: 1216,
    height: 2581,
    alt: "Katanagatari's detail page on the phone with the status sheet open: the status, the progress and the score over the community's own spread of scores.",
    caption: "Android — a title, with its entry open",
    avif: [{ w: 1216, src: s19_avif_1216 }, { w: 608, src: s19_avif_608 }],
    webp: [{ w: 608, src: s19_webp_608 }],
    jpg: [{ w: 608, src: s19_jpg_608 }],
  },
  {
    id: "phone-search",
    kind: "phone",
    width: 1216,
    height: 2581,
    alt: "The search page on the phone with the results for “haikyu” as a cover grid.",
    caption: "Android — search",
    avif: [{ w: 1216, src: s20_avif_1216 }, { w: 608, src: s20_avif_608 }],
    webp: [{ w: 608, src: s20_webp_608 }],
    jpg: [{ w: 608, src: s20_jpg_608 }],
  },
  {
    id: "phone-more",
    kind: "phone",
    width: 1216,
    height: 2581,
    alt: "The More sheet on the phone listing the remaining screens.",
    caption: "Android — the More sheet",
    avif: [{ w: 1216, src: s21_avif_1216 }, { w: 608, src: s21_avif_608 }],
    webp: [{ w: 608, src: s21_webp_608 }],
    jpg: [{ w: 608, src: s21_jpg_608 }],
  },
];

export const shot = (id: string): Shot => {
  const s = SHOTS.find((x) => x.id === id);
  if (!s) throw new Error(`no screenshot ${id}`);
  return s;
};
