import {
  ArrowLeft,
  ArrowRight,
  Bell,
  BellOff,
  Check,
  CheckCheck,
  Command,
  Copy,
  ExternalLink,
  FileText,
  Pencil,
  Plus,
  RefreshCw,
  RotateCw,
  Search,
  SearchCheck,
  Settings,
  Share2,
  Star,
  Tag,
  Trash2,
  Undo2,
  X,
  type LucideIcon,
} from "lucide-react";
import type { ActionId } from "@/lib/actions";

/** Lucide only, and one per action, so the two renderers cannot illustrate the same action differently. */
export const ACTION_ICON: Record<ActionId, LucideIcon> = {
  open: FileText,
  openAniList: ExternalLink,
  share: Share2,
  copySelection: Copy,
  addToList: Plus,
  edit: Pencil,
  plusOne: Plus,
  plusVolume: Plus,
  complete: CheckCheck,
  setStatus: Tag,
  setScore: Star,
  removeFromList: Trash2,
  muteAiring: BellOff,
  unmuteAiring: Bell,
  scrobbleNow: Check,
  scrobbleCancel: X,
  fixMatch: SearchCheck,
  clearOverride: Undo2,
  back: ArrowLeft,
  forward: ArrowRight,
  reload: RotateCw,
  palette: Command,
  settings: Settings,
  sync: RefreshCw,
  search: Search,
};
