// Generated by `cargo test` from the Rust command signatures; never edited by hand, see CLAUDE.md.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	anilistAuthInfo: () => __TAURI_INVOKE<AuthInfo>("anilist_auth_info"),
	setClientId: (clientId: string) => typedError<null, string>(__TAURI_INVOKE("set_client_id", { clientId })),
	/**  The authorize URL for the manual-paste flow; no callback server runs, so no `state` is needed. */
	anilistLoginUrl: () => typedError<string, string>(__TAURI_INVOKE("anilist_login_url")),
	/**  Starts the one-click login: spins up the localhost callback server and returns the authorize URL. */
	anilistStartLogin: () => typedError<string, string>(__TAURI_INVOKE("anilist_start_login")),
	anilistConnect: (token: string) => typedError<any, string>(__TAURI_INVOKE("anilist_connect", { token })),
	/**  Returns the cached viewer if a token is stored, without an API call, so startup works offline. */
	anilistSession: () => __TAURI_INVOKE<any | null>("anilist_session"),
	anilistLogout: () => __TAURI_INVOKE<void>("anilist_logout"),
	/**  Refetches the viewer and replaces the cached blob, on demand only, since `anilist_session` never goes online. */
	refreshViewer: () => typedError<any, string>(__TAURI_INVOKE("refresh_viewer")),
	/**  Generic GraphQL proxy: Rust attaches the token, paces it, and serves an allowlisted source from cache within its TTL. */
	anilistQuery: (query: string, variables: any | null, source: string | null, cache: {
	ttlSec: number,
	mediaId: number | null,
} | null) => typedError<any, string>(__TAURI_INVOKE("anilist_query", { query, variables, source, cache })),
	/**  Loads the list: the cache inside the window, the cache plus a background refresh past it, AniList when forced. */
	fetchMediaList: (userId: number, mediaType: string, force: boolean | null) => typedError<ListResult, string>(__TAURI_INVOKE("fetch_media_list", { userId, mediaType, force })),
	/**  The last cached list with no network access, a head start on the fetch; `from_cache` stays false, it is not a fallback. */
	cachedMediaList: (userId: number, mediaType: string) => __TAURI_INVOKE<{
	/**  true if the data comes from the local cache (offline) */
	fromCache: boolean,
	/**  number of changes not yet synced */
	pending: number,
	/**  When this list was last fetched from AniList, unix seconds; the frontend seeds its own staleness from it. */
	fetchedAt: number,
	lists: any,
} | null>("cached_media_list", { userId, mediaType }),
	/**  Saves a list entry; offline, the change is queued and synced later. */
	saveListEntry: (input: any) => typedError<MutationResult, string>(__TAURI_INVOKE("save_list_entry", { input })),
	/**  Applies one change to many entries in a few requests, rather than one mutation per entry against the rate budget. */
	bulkSaveListEntries: (input: BulkSaveInput) => typedError<BulkResult_Serialize, string>(__TAURI_INVOKE("bulk_save_list_entries", { input })),
	deleteListEntry: (id: number) => typedError<MutationResult, string>(__TAURI_INVOKE("delete_list_entry", { id })),
	/**  Manually triggered sync of the offline queue (e.g. a button in the UI). */
	flushQueue: () => typedError<number, string>(__TAURI_INVOKE("flush_queue")),
	/**  Discards one queued edit, scoped to the signed-in account in the DELETE itself since the id may straddle a sign-out. */
	discardQueuedEdit: (id: number) => typedError<boolean, string>(__TAURI_INVOKE("discard_queued_edit", { id })),
	/**  The state of the sync, for the panel behind the pending badge. */
	syncStatus: () => typedError<SyncStatus, string>(__TAURI_INVOKE("sync_status")),
	/**  Fetches a bio image as one bounded Rust request and returns a `data:` URI; never widen `img-src` instead. */
	fetchBioImage: (url: string) => typedError<string, string>(__TAURI_INVOKE("fetch_bio_image", { url })),
	getBlurAdult: () => __TAURI_INVOKE<boolean>("get_blur_adult"),
	setBlurAdult: (blur: boolean) => typedError<null, string>(__TAURI_INVOKE("set_blur_adult", { blur })),
	getProfileMode: () => __TAURI_INVOKE<string>("get_profile_mode"),
	/**  Switches into account-free local mode and deletes the token, which survives a reinstall the database does not. */
	enableLocalMode: () => typedError<null, string>(__TAURI_INVOKE("enable_local_mode")),
	/**  Loads the local list for a media type, shaped exactly like the online `ListResult` so the UI is identical. */
	localFetchList: (mediaType: string) => typedError<ListResult, string>(__TAURI_INVOKE("local_fetch_list", { mediaType })),
	/**  Saves a local entry; a first add supplies `media` so the list renders offline, later edits may omit it. */
	localSaveEntry: (input: any) => typedError<MutationResult, string>(__TAURI_INVOKE("local_save_entry", { input })),
	/**  Deletes a local entry; in local mode the frontend entry id equals the media id. */
	localDeleteEntry: (id: number) => typedError<MutationResult, string>(__TAURI_INVOKE("local_delete_entry", { id })),
	/**  All local rows across both media types with their media metadata, for the sign-in merge's conflict prompt. */
	localAllEntries: () => __TAURI_INVOKE<any>("local_all_entries"),
	/**  Currently detected playback (poll loop state). */
	getNowPlaying: () => __TAURI_INVOKE<{
	process: string,
	streaming: boolean,
	/**  "ANIME" or "MANGA" — for manga, `episode` carries the chapter number */
	mediaType: string,
	rawTitle: string,
	parsedTitle: string,
	/**  The season the parse carried; half of a correction's key, so the picker has to send it back. */
	season: number | null,
	/**  The episode as resolved: the source's number plus any correction offset, then the relations redirect. */
	episode: number | null,
	/**  The episode as the source reported it; re-resolving from the shifted one would shift it again. */
	sourceEpisode: number | null,
	/**  AniList media ID on a successful match against the list */
	mediaId: number | null,
	matchedTitle: string | null,
	/**  Whether this match came from the user's own correction; drives the "undo" affordance, nothing else. */
	overridden: boolean,
	/**  Current list progress of the matched entry */
	progress: number | null,
	totalEpisodes: number | null,
	/**  The episode's own name where the source had one, for the card; never part of any key. */
	episodeTitle: string | null,
} | null>("get_now_playing"),
	getScrobbleSettings: () => __TAURI_INVOKE<ScrobbleSettings>("get_scrobble_settings"),
	setScrobbleSettings: (enabled: boolean, confirm: boolean, delayMin: number, gapAuto: boolean) => typedError<null, string>(__TAURI_INVOKE("set_scrobble_settings", { enabled, confirm, delayMin, gapAuto })),
	/**  Confirms the pending auto-update immediately (also from Blocked). */
	scrobbleNow: () => typedError<null, string>(__TAURI_INVOKE("scrobble_now")),
	/**  Discards the pending auto-update for this episode. */
	scrobbleCancel: () => typedError<null, string>(__TAURI_INVOKE("scrobble_cancel")),
	getDiscordSettings: () => __TAURI_INVOKE<DiscordSettings>("get_discord_settings"),
	setDiscordSettings: (enabled: boolean, appId: string) => typedError<null, string>(__TAURI_INVOKE("set_discord_settings", { enabled, appId })),
	/**  Reports the page the user is on, so the idle Discord presence can show "Looking at <page>". */
	setUiPage: (page: string) => __TAURI_INVOKE<void>("set_ui_page", { page }),
	getAutostart: () => __TAURI_INVOKE<boolean>("get_autostart"),
	setAutostart: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_autostart", { enabled })),
	/**  Mirrors the interface language into kv, because Rust composes notifications, bell rows and the tray menu. */
	setUiLanguage: (language: string) => typedError<null, string>(__TAURI_INVOKE("set_ui_language", { language })),
	/**  Mirrors the title language into kv, because Rust spells titles in notifications, the tray, widgets and Discord. */
	setTitleLanguage: (language: string) => typedError<null, string>(__TAURI_INVOKE("set_title_language", { language })),
	/**  Whether new-episode desktop notifications are enabled (default on). */
	getAiringNotify: () => __TAURI_INVOKE<boolean>("get_airing_notify"),
	setAiringNotify: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_airing_notify", { enabled })),
	/**  The muted titles, sorted by the stored title; Settings re-sorts by the spelling it shows. */
	listAiringMutes: () => __TAURI_INVOKE<AiringMute[]>("list_airing_mutes"),
	/**  Mutes or unmutes one title's new-episode notifications, then re-times the watcher's sleep. */
	setAiringMute: (mediaId: number, title: string, muted: boolean) => typedError<null, string>(__TAURI_INVOKE("set_airing_mute", { mediaId, title, muted })),
	/**  The background-notification interval in minutes, 0 meaning off; one kv key both platforms read. */
	getNotifSchedule: () => __TAURI_INVOKE<number>("get_notif_schedule"),
	setNotifSchedule: (minutes: number) => typedError<null, string>(__TAURI_INVOKE("set_notif_schedule", { minutes })),
	/**  On-hold reminder settings (disabled by default). */
	getStaleSettings: () => __TAURI_INVOKE<StaleSettings>("get_stale_settings"),
	setStaleSettings: (enabled: boolean, months: number) => typedError<null, string>(__TAURI_INVOKE("set_stale_settings", { enabled, months })),
	/**  Whether sequel-announcement notifications are enabled (default off). */
	getSequelNotify: () => __TAURI_INVOKE<boolean>("get_sequel_notify"),
	setSequelNotify: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_sequel_notify", { enabled })),
	/**  Recent notifications, newest first (for the bell dropdown). */
	getNotifications: () => __TAURI_INVOKE<NotificationRow[]>("get_notifications"),
	/**  Everything a bug report needs in one round trip, so a reporter cannot end up with half a picture. */
	diagnostics: () => __TAURI_INVOKE<Diagnostics>("diagnostics"),
	/**  The same facts as a markdown block for an issue; redacted, because the data folder names a person. */
	diagnosticsReport: (redact: boolean) => __TAURI_INVOKE<string>("diagnostics_report", { redact }),
	/**  The newest log entries, newest first. */
	getLogs: (limit: number | null) => __TAURI_INVOKE<LogEntry[]>("get_logs", { limit }),
	getUiZoom: () => __TAURI_INVOKE<number>("get_ui_zoom"),
	/**  Stores and applies the zoom, answering with the clamped value so the pane shows what was applied. */
	setUiZoom: (percent: number) => typedError<number, string>(__TAURI_INVOKE("set_ui_zoom", { percent })),
	/**  A crash or unhandled rejection from the WebView, logged beside the backend's so the two line up in order. */
	logFrontendError: (message: string, stack: string | null) => __TAURI_INVOKE<void>("log_frontend_error", { message, stack }),
	getLogDebug: () => __TAURI_INVOKE<boolean>("get_log_debug"),
	setLogDebug: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_log_debug", { enabled })),
	/**  Writes the report and the log to a file the user picks, through a Rust-driven dialog like `save_image`. */
	exportDiagnostics: (redact: boolean) => typedError<boolean, string>(__TAURI_INVOKE("export_diagnostics", { redact })),
	unreadNotificationCount: () => __TAURI_INVOKE<number>("unread_notification_count"),
	markNotificationRead: (id: number) => typedError<null, string>(__TAURI_INVOKE("mark_notification_read", { id })),
	markAllNotificationsRead: () => typedError<null, string>(__TAURI_INVOKE("mark_all_notifications_read")),
	/**  Saves an image through a native dialog; `data` is base64, since a typed array crosses the bridge as JSON numbers. */
	saveImage: (data: string, defaultName: string, format: string) => typedError<boolean, string>(__TAURI_INVOKE("save_image", { data, defaultName, format })),
	/**  Saves caller-supplied text through the same dialog as `export_diagnostics`; the WebView gets no filesystem door. */
	saveText: (contents: string, defaultName: string, filterLabel: string, extension: string) => typedError<boolean, string>(__TAURI_INVOKE("save_text", { contents, defaultName, filterLabel, extension })),
	/**  The running four-part version, shown in the About window. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**  Compares the running version against the selected channel's manifest; `force: false` respects the daily throttle. */
	checkForUpdates: (force: boolean) => typedError<UpdateInfo, string>(__TAURI_INVOKE("check_for_updates", { force })),
	getUpdateChannel: () => __TAURI_INVOKE<string>("get_update_channel"),
	setUpdateChannel: (channel: string) => typedError<null, string>(__TAURI_INVOKE("set_update_channel", { channel })),
	/**  Whether Karasu checks for updates automatically on startup; manual checks from About always work. */
	getUpdateCheckAuto: () => __TAURI_INVOKE<boolean>("get_update_check_auto"),
	setUpdateCheckAuto: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_update_check_auto", { enabled })),
	getContentFilter: () => __TAURI_INVOKE<string>("get_content_filter"),
	setContentFilter: (level: string) => typedError<null, string>(__TAURI_INVOKE("set_content_filter", { level })),
	/**  Checks the selected channel's manifest, downloads a newer build into the stash and notifies once it is there. */
	downloadPendingUpdate: () => typedError<{
	version: string,
	notes: string | null,
} | null, string>(__TAURI_INVOKE("download_pending_update")),
	/**  What is sitting in the stash, so About can show a download the startup check made. */
	pendingUpdate: () => __TAURI_INVOKE<{
	version: string,
	notes: string | null,
} | null>("pending_update"),
	/**  Installs the stashed update and restarts the app; on success this call does not return. */
	installPendingUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_pending_update")),
	apkUpdaterAvailable: () => __TAURI_INVOKE<boolean>("apk_updater_available"),
	apkUpdateState: () => __TAURI_INVOKE<ApkUpdateState>("apk_update_state"),
	apkDownload: (forceMetered: boolean | null) => typedError<ApkUpdateState, string>(__TAURI_INVOKE("apk_download", { forceMetered })),
	apkInstall: () => typedError<null, string>(__TAURI_INVOKE("apk_install")),
	apkOpenInstallPermission: () => typedError<null, string>(__TAURI_INVOKE("apk_open_install_permission")),
	apkDiscard: () => __TAURI_INVOKE<void>("apk_discard"),
	apkPromptIfReady: () => __TAURI_INVOKE<boolean>("apk_prompt_if_ready"),
	/**  The "download over mobile data" switch; read on Android only, kept everywhere so the setting has one home. */
	getApkDownloadMetered: () => __TAURI_INVOKE<boolean>("get_apk_download_metered"),
	setApkDownloadMetered: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_apk_download_metered", { enabled })),
	/**  Windows' Accessibility text-size multiplier; WebView2 ignores it, so the frontend sets the root font size. */
	getTextScale: () => __TAURI_INVOKE<number>("get_text_scale"),
	getMediaDetection: () => __TAURI_INVOKE<boolean>("get_media_detection"),
	setMediaDetection: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_media_detection", { enabled })),
	/**  Every media session for the Settings diagnostic; a `Result`, because an empty list and an unreachable service differ. */
	mediaSessions: () => typedError<MediaSession[], string>(__TAURI_INVOKE("media_sessions")),
	getJellyfinSettings: () => __TAURI_INVOKE<JellyfinSettings>("get_jellyfin_settings"),
	/**  Saves the settings outside sign-in; an external address answering as another server is refused, an unreachable one kept. */
	setJellyfinSettings: (url: string, device: string, externalUrl: string) => typedError<null, string>(__TAURI_INVOKE("set_jellyfin_settings", { url, device, externalUrl })),
	/**  Exchanges a username and password for an access token; signing in as a user scopes `/Sessions` to this account. */
	jellyfinSignIn: (url: string, username: string, password: string) => typedError<JellyfinSettings, string>(__TAURI_INVOKE("jellyfin_sign_in", { url, username, password })),
	jellyfinSignOut: () => typedError<JellyfinSettings, string>(__TAURI_INVOKE("jellyfin_sign_out")),
	/**  Lists the account's sessions, non-matching ones included, because the device filter is otherwise undiagnosable. */
	testJellyfin: () => typedError<JellyfinTest, string>(__TAURI_INVOKE("test_jellyfin")),
	getJellyfinBackground: () => __TAURI_INVOKE<JellyfinBackground>("get_jellyfin_background"),
	/**  Stores the choice; the scrobbler's next tick starts or stops the service. */
	setJellyfinBackground: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_jellyfin_background", { enabled })),
	/**  Opens Android's exemption dialog; the desktop arm refuses, and the pane never shows the button there. */
	requestBatteryExemption: () => typedError<null, string>(__TAURI_INVOKE("request_battery_exemption")),
	/**  Every Jellyfin server that answers the LAN broadcast and confirms itself; a button press, never a poll. */
	discoverJellyfinServers: () => typedError<DiscoveredServer[], string>(__TAURI_INVOKE("discover_jellyfin_servers")),
	/**  What the server at `url` says it is — name, version, id — anonymously. */
	probeJellyfinServer: (url: string) => typedError<ServerInfo, string>(__TAURI_INVOKE("probe_jellyfin_server", { url })),
	platformInfo: () => __TAURI_INVOKE<PlatformInfo>("platform_info"),
	/**  The desktop's or the phone's accent colour as `#rrggbb`, or nothing where the platform does not publish one. */
	systemAccent: () => __TAURI_INVOKE<string | null>("system_accent"),
	getCloseToTray: () => __TAURI_INVOKE<CloseToTray>("get_close_to_tray"),
	setCloseToTray: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_close_to_tray", { enabled })),
	getGlobalHotkey: () => __TAURI_INVOKE<string | null>("get_global_hotkey"),
	/**  Registers (or on Wayland validates) before it stores, so a rejected key never returns at every startup. */
	setGlobalHotkey: (accelerator: string | null) => typedError<null, string>(__TAURI_INVOKE("set_global_hotkey", { accelerator })),
	/**  Where the summon hotkey stands: which backend holds it and, for the portal, what the desktop answered. */
	globalHotkeyStatus: () => __TAURI_INVOKE<HotkeyStatus>("global_hotkey_status"),
	/**  Opens the desktop's own dialog for the summon key, where the portal's second version offers one. */
	configureGlobalHotkey: () => typedError<null, string>(__TAURI_INVOKE("configure_global_hotkey")),
	/**  `save_text`'s opposite: the WebView asks for a kind of file and receives bounded text, never a path. */
	openText: (filterLabel: string, extension: string) => typedError<string | null, string>(__TAURI_INVOKE("open_text", { filterLabel, extension })),
	getBackupSettings: () => __TAURI_INVOKE<BackupSettings>("get_backup_settings"),
	setBackupSettings: (enabled: boolean, keep: number) => typedError<null, string>(__TAURI_INVOKE("set_backup_settings", { enabled, keep })),
	/**  Opens the backup folder in the file manager, creating it first so the button is never a dead end. */
	openBackupDir: () => typedError<null, string>(__TAURI_INVOKE("open_backup_dir")),
	getMpvIpc: () => __TAURI_INVOKE<MpvIpcSettings>("get_mpv_ipc"),
	setMpvIpc: (enabled: boolean, path: string, launchPath: string) => typedError<null, string>(__TAURI_INVOKE("set_mpv_ipc", { enabled, path, launchPath })),
	listDetectionOverrides: () => __TAURI_INVOKE<DetectionOverride[]>("list_detection_overrides"),
	/**  Stores a correction against the parse and applies it now, since the poll only rebuilds a match when the title changes. */
	setDetectionOverride: (title: string, season: number | null, mediaType: string, mediaId: number, displayTitle: string, episodeOffset: number | null) => typedError<null, string>(__TAURI_INVOKE("set_detection_override", { title, season, mediaType, mediaId, displayTitle, episodeOffset })),
	/**  Forgets one, giving the matcher its guess back. */
	clearDetectionOverride: (title: string, season: number | null, mediaType: string) => typedError<null, string>(__TAURI_INVOKE("clear_detection_override", { title, season, mediaType })),
	getPortableStatus: () => __TAURI_INVOKE<PortableStatus>("get_portable_status"),
	/**  Enables portable mode: the database and token are copied first and the marker written last, because it is live. */
	enablePortable: (replace: boolean | null) => typedError<null, string>(__TAURI_INVOKE("enable_portable", { replace })),
	/**  Disables portable mode by removing the marker, leaving the portable folder alone: a switch, not a delete. */
	disablePortable: () => typedError<null, string>(__TAURI_INVOKE("disable_portable")),
	getLibraryPath: () => __TAURI_INVOKE<string | null>("get_library_path"),
	setLibraryPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("set_library_path", { path })),
	/**  Opens a native folder picker and returns the chosen path. */
	pickLibraryFolder: () => __TAURI_INVOKE<string | null>("pick_library_folder"),
	/**  The most recent scan's full index; only the Library screen needs it, everyone else reads `get_library_episodes`. */
	getLibraryIndex: () => __TAURI_INVOKE<LibraryEntry_Serialize[]>("get_library_index"),
	/**  Just which episodes exist per media id, so the launch-time read does not ship every absolute path over IPC. */
	getLibraryEpisodes: () => __TAURI_INVOKE<{ [key in string]: number[] }>("get_library_episodes"),
	/**  The folder and what the last scan made of it, so the row has something to show after a restart. */
	getLibraryStatus: () => __TAURI_INVOKE<LibraryStatus>("get_library_status"),
	/**  Scans the configured folder and rebuilds the index; `async` is load-bearing, a blocking command froze the window. */
	scanLibrary: () => typedError<ScanSummary_Serialize, string>(__TAURI_INVOKE("scan_library")),
	/**  Files the last scan could not place, grouped by what it read them as. */
	getLibraryUnmatched: () => __TAURI_INVOKE<UnmatchedGroup[]>("get_library_unmatched"),
	/**  Points every file of this parse at `media_id` in memory at once; the override row makes the next scan agree. */
	setLibraryMatch: (title: string, season: number, mediaId: number) => typedError<LibraryEntry_Serialize[], string>(__TAURI_INVOKE("set_library_match", { title, season, mediaId })),
	/**  Drops a correction; the matcher is not re-run, so the files land in "unplaced" until the next scan. */
	clearLibraryMatch: (title: string, season: number) => typedError<LibraryEntry_Serialize[], string>(__TAURI_INVOKE("clear_library_match", { title, season })),
	/**  Confirms a season split in memory at once; the rows `plan_redirect` produces make the next scan and restart agree. */
	setLibraryRedirect: (mediaId: number, from: number, to: number, dstMediaId: number, dstStart: number) => typedError<LibraryEntry_Serialize[], string>(__TAURI_INVOKE("set_library_redirect", { mediaId, from, to, dstMediaId, dstStart })),
	/**  Removes a season split, giving the range back to a sibling of the same parse, or to "unplaced" when none remains. */
	clearLibraryRedirect: (title: string, season: number, epFrom: number) => typedError<LibraryEntry_Serialize[], string>(__TAURI_INVOKE("clear_library_redirect", { title, season, epFrom })),
	/**  The confirmed splits for the Settings list, so a split can be undone on its own rather than with the whole key. */
	listLibraryRedirects: () => __TAURI_INVOKE<LibraryRedirectRow[]>("list_library_redirects"),
	/**  Opens the next unwatched episode of `media_id` in the default player, for detection to pick up as usual. */
	playNext: (mediaId: number) => typedError<null, string>(__TAURI_INVOKE("play_next", { mediaId })),
	/**  Opens one specific episode, which the library page lets the user pick and `play_next` cannot express. */
	playEpisode: (mediaId: number, episode: number) => typedError<null, string>(__TAURI_INVOKE("play_episode", { mediaId, episode })),
};

/* Types */
/**  A title whose new episodes Karasu stays quiet about, with the title it was muted under. */
export type AiringMute = {
	mediaId: number,
	title: string,
};

/**  What About and the bell show; `available` is false on every platform but an Android release build. */
export type ApkUpdateState = {
	available: boolean,
	/**  `none` · `downloading` · `ready` · `blocked`. */
	status: string,
	version: string | null,
	/**  For `blocked`: `metered` · `space` · `signature` · `stale` · `foreground` · `network`. */
	reason: string | null,
	needsInstallPermission: boolean,
	received: number,
	total: number,
};

export type AuthInfo = {
	/**  true if a client ID is compiled in (login works without any setup) */
	hasBuiltinClientId: boolean,
	customClientId: string | null,
	/**  The redirect URL an API client must register, built from `login::AUTH_CALLBACK_PORT` so the port has one origin. */
	callbackUrl: string,
};

export type BackupSettings = {
	enabled: boolean,
	keep: number,
	/**  Where the files land, shown in the settings hint so nobody has to ask. */
	dir: string,
};

/**  Which of the two addresses a request went to. */
export type Base = "local" | "external";

/**  What a bulk edit managed and what stopped it; two fields, because a run can both write hundreds and fail. */
export type BulkResult = BulkResult_Serialize | BulkResult_Deserialize;

/**  What a bulk edit managed and what stopped it; two fields, because a run can both write hundreds and fail. */
export type BulkResult_Deserialize = {
	updated: number,
	/**  The failure that ended the run; whatever `updated` counts is already written and not undone by it. */
	error: string | null,
};

/**  What a bulk edit managed and what stopped it; two fields, because a run can both write hundreds and fail. */
export type BulkResult_Serialize = {
	updated: number,
	/**  The failure that ended the run; whatever `updated` counts is already written and not undone by it. */
	error?: string | null,
};

/**  One change for many entries; a struct because specta's function support stops at ten arguments. */
export type BulkSaveInput = {
	ids: number[],
	status: string | null,
	/**  The format-independent raw score, never a float. */
	scoreRaw: number | null,
	progress: number | null,
	progressVolumes: number | null,
	repeat: number | null,
	private: boolean | null,
	/**  Back onto the status lists, for entries a deleted custom list would otherwise leave on no list at all. */
	hiddenFromStatusLists: boolean | null,
	/**  `FuzzyDateInput`, forwarded as an opaque `{year, month, day}` because every part is nullable. */
	startedAt: any | null,
	completedAt: any | null,
};

/**  What the frontend asks the passthrough to cache: a TTL, and the media a detail answer is about so an edit evicts it. */
export type CacheOpts = {
	ttlSec: number,
	mediaId: number | null,
};

export type CloseToTray = {
	/**  What closing the window does right now. */
	enabled: boolean,
	/**  Whether a tray icon was created at startup, so the screen can say why the setting reads as it does. */
	tray: boolean,
};

/**  Enough about a database file to say how old it is and whether it looks used. */
export type DatabaseInfo = {
	path: string,
	bytes: number,
	/**  Last modified in milliseconds since the epoch, or 0 when the filesystem will not say. */
	modifiedMs: number,
};

/**  One detection correction: what was detected, and what it really is. */
export type DetectionOverride = {
	/**  The parsed title this fires on — what detection saw. */
	title: string,
	/**  `-1` where the parse carried no season. */
	season: number,
	mediaType: string,
	mediaId: number,
	/**  The chosen entry's title, stored so the Settings list and an off-list entry read correctly without a request. */
	displayTitle: string,
	/**  Added to the detected episode; signed because a source may number ahead of AniList as easily as behind. */
	episodeOffset: number,
};

export type Diagnostics = {
	/**  The four-part `MAJOR.MINOR.PATCH.COMMIT#`; the commit counter is the only precise build identifier. */
	version: string,
	os: string,
	appImage: boolean,
	portable: boolean,
	/**  Where the database lives; redacted by `render`, not here, so the viewer can show the owner the real path. */
	dataDir: string,
	tray: boolean,
	schema: number,
	/**  Which manifest the updater polls; the same four-part version can run on either channel. */
	updateChannel: string,
	queued: number,
	/**  Whether a token exists. Never the token. */
	signedIn: boolean,
	profileMode: string,
	libraryConfigured: boolean,
	libraryFiles: number,
	libraryMatched: number,
	mediaSessions: boolean,
	jellyfin: boolean,
	/**  Which Jellyfin address the last successful request went to, `local` or `external`; it names no host. */
	jellyfinBase: string | null,
	/**  The mpv IPC pipe; it outranks every other source, so a report has to say whether it was on. */
	mpv: boolean,
	logDebug: boolean,
	/**  AniList requests per source since the app started; the budget is shared, so a report has to say who spent it. */
	anilistRequests: ([string, number])[],
	/**  HTTP 429 answers since the app started. */
	anilistThrottled: number,
	/**  The limiter's last measured headroom, `remaining/limit`, or none before the first header. */
	anilistBudget: [number, number] | null,
	linux: LinuxInfo | null,
};

export type DiscordSettings = {
	enabled: boolean,
	appId: string,
	/**  true if an application ID is compiled in */
	hasBuiltinAppId: boolean,
};

/**  A server that answered the broadcast, confirmed by its own info endpoint. */
export type DiscoveredServer = {
	name: string,
	address: string,
	id: string,
	/**  From the probe; `None` for a reply that was never confirmed. */
	version: string | null,
};

export type DownloadedUpdate = {
	version: string,
	notes: string | null,
};

/**  Which mechanism holds the summon hotkey in this session. */
export type HotkeyBackend = "grab" | "portal";

/**  How far the binding got; a grab is settled the moment it registers, the portal answers later. */
export type HotkeyState = "off" | "pending" | "bound" | "noPortal" | "noAppId" | "denied" | "failed";

export type HotkeyStatus = {
	backend: HotkeyBackend,
	state: HotkeyState,
	/**  The desktop's own spelling of the bound key, which need not be the one Karasu proposed. */
	trigger: string | null,
	/**  Whether the desktop can open its own dialog to change the key (the portal's second version). */
	configurable: boolean,
};

export type JellyfinBackground = {
	enabled: boolean,
	/**  Whether this platform has the service at all (Android only), so the pane can leave the rows out elsewhere. */
	supported: boolean,
	/**  Whether Android has exempted Karasu from battery optimisation; `None` where it does not apply or could not be asked. */
	batteryExempt: boolean | null,
};

export type JellyfinSettings = {
	url: string,
	/**  Whether an access token is stored; the token itself never leaves the credential store. */
	connected: boolean,
	/**  The signed-in account, so Settings can show who that is. */
	userName: string,
	/**  The server's own name from `/System/Info/Public` at sign-in; empty for a sign-in older than that probe. */
	serverName: string,
	device: string,
	/**  This machine's name, so the UI can offer it as the default. */
	localDevice: string,
	/**  The optional second address; empty for none. */
	externalUrl: string,
	/**  Whether the external address has answered as the same server from here; `None` when there is none. */
	externalVerified: boolean | null,
	/**  Whether the external address would carry the token over plain http, which the pane warns about. */
	externalPlainHttp: boolean,
};

/**  The Test-connection answer: the sessions, and which address answered. */
export type JellyfinTest = {
	sessions: SessionSummary[],
	base: Base,
	url: string,
};

/**  Severity, ordered `Error < Warn < Info < Debug`, so a threshold check is a plain comparison. */
export type Level = "error" | "warn" | "info" | "debug";

/**  Which episodes of a matched entry are on disk; `episodes` stays a bare sorted list for existing callers. */
export type LibraryEntry = LibraryEntry_Serialize | LibraryEntry_Deserialize;

/**  Which episodes of a matched entry are on disk; `episodes` stays a bare sorted list for existing callers. */
export type LibraryEntry_Deserialize = {
	mediaId: number,
	episodes: number[],
	files: LibraryFile[],
	/**  Matcher confidence; `1.0` is the exact-title short circuit and anything below reads as "close" on screen. */
	score: number,
	/**  The release names that led here — what a correction has to be keyed on. */
	sources: TitleKey[],
	/**  Placed by the user rather than the matcher, so the screen can say so instead of showing a confidence. */
	manual: boolean,
	/**  More files than the entry has episodes, usually a next season in one folder; detection only, nothing re-pointed. */
	overflow: Overflow_Deserialize | null,
};

/**  Which episodes of a matched entry are on disk; `episodes` stays a bare sorted list for existing callers. */
export type LibraryEntry_Serialize = {
	mediaId: number,
	episodes: number[],
	files: LibraryFile[],
	/**  Matcher confidence; `1.0` is the exact-title short circuit and anything below reads as "close" on screen. */
	score: number,
	/**  The release names that led here — what a correction has to be keyed on. */
	sources: TitleKey[],
	/**  Placed by the user rather than the matcher, so the screen can say so instead of showing a confidence. */
	manual: boolean,
	/**  More files than the entry has episodes, usually a next season in one folder; detection only, nothing re-pointed. */
	overflow?: Overflow_Serialize | null,
};

/**  One episode present on disk. */
export type LibraryFile = {
	episode: number,
	path: string,
};

/**  One confirmed split for the Settings list, keyed on the parse, which is what `clear_library_redirect` deletes by. */
export type LibraryRedirectRow = {
	title: string,
	season: number,
	epFrom: number,
	epTo: number,
	mediaId: number,
	dstStart: number,
};

/**  What the library screen's path row says, without needing a scan to say it. */
export type LibraryStatus = {
	path: string | null,
	/**  Video files the last scan walked past, matched or not. */
	filesSeen: number,
	/**  Titles it could identify. */
	matched: number,
};

/**  The Linux-only half; `None` on Windows, so the shape says which platform produced it. */
export type LinuxInfo = {
	/**  `PRETTY_NAME` from `/etc/os-release`. */
	distro: string | null,
	/**  `XDG_CURRENT_DESKTOP`; GNOME needs an extension before a tray icon appears at all. */
	desktop: string | null,
	/**  `XDG_SESSION_TYPE`; under Wayland one application cannot read another's window titles at all. */
	session: string | null,
};

export type ListResult = {
	/**  true if the data comes from the local cache (offline) */
	fromCache: boolean,
	/**  number of changes not yet synced */
	pending: number,
	/**  When this list was last fetched from AniList, unix seconds; the frontend seeds its own staleness from it. */
	fetchedAt: number,
	lists: any,
};

/**  One line; `target` is the subsystem, so the viewer can group without parsing the message. */
export type LogEntry = {
	ms: number,
	level: Level,
	target: string,
	message: string,
};

/**  One media session as the desktop sees it, serialized straight into the Settings diagnostic. */
export type MediaSession = {
	/**  Source app: an executable path or package family name on Windows, a D-Bus bus name on Linux. */
	appId: string,
	title: string,
	artist: string,
	album: string,
	/**  "music" | "video" | "image" | "unknown" */
	playbackType: string,
	/**  "playing" | "paused" | "stopped" | "changing" | "opened" | "closed" */
	status: string,
	/**  What is being played, when the source says; MPRIS publishes `xesam:url`, SMTC has no equivalent. */
	url: string,
};

export type MpvIpcSettings = {
	enabled: boolean,
	/**  The effective path — the stored one, or the platform default. */
	path: string,
	/**  What the settings hint tells the user to put in `mpv.conf`. */
	defaultPath: string,
	/**  The player binary for library launches, empty for the default player. */
	launchPath: string,
};

export type MutationResult = {
	/**  true if the change was queued offline */
	queued: boolean,
	entry: any | null,
};

/**  One in-app notification (mirrors a shown desktop toast). */
export type NotificationRow = {
	id: number,
	kind: string,
	title: string,
	body: string,
	createdMs: number,
	/**  What the bell row opens; `None` for the update notice, a dropped-queue report and every row older than v15. */
	mediaId: number | null,
	read: boolean,
};

export type NowPlaying = {
	process: string,
	streaming: boolean,
	/**  "ANIME" or "MANGA" — for manga, `episode` carries the chapter number */
	mediaType: string,
	rawTitle: string,
	parsedTitle: string,
	/**  The season the parse carried; half of a correction's key, so the picker has to send it back. */
	season: number | null,
	/**  The episode as resolved: the source's number plus any correction offset, then the relations redirect. */
	episode: number | null,
	/**  The episode as the source reported it; re-resolving from the shifted one would shift it again. */
	sourceEpisode: number | null,
	/**  AniList media ID on a successful match against the list */
	mediaId: number | null,
	matchedTitle: string | null,
	/**  Whether this match came from the user's own correction; drives the "undo" affordance, nothing else. */
	overridden: boolean,
	/**  Current list progress of the matched entry */
	progress: number | null,
	totalEpisodes: number | null,
	/**  The episode's own name where the source had one, for the card; never part of any key. */
	episodeTitle: string | null,
};

/**  The facts the season-split card needs, computed at reindex time. */
export type Overflow = Overflow_Serialize | Overflow_Deserialize;

/**  The facts the season-split card needs, computed at reindex time. */
export type Overflow_Deserialize = {
	/**  AniList's episode count for the matched entry. */
	knownEpisodes: number,
	/**  How many on-disk episodes lie beyond it. */
	extraFiles: number,
	/**  The first overflowing episode number, as the files spell it. */
	firstExtra: number,
	/**  What the community rules say the overflow is: a pre-selection for the card, never applied without confirmation. */
	hint: SplitHint | null,
};

/**  The facts the season-split card needs, computed at reindex time. */
export type Overflow_Serialize = {
	/**  AniList's episode count for the matched entry. */
	knownEpisodes: number,
	/**  How many on-disk episodes lie beyond it. */
	extraFiles: number,
	/**  The first overflowing episode number, as the files spell it. */
	firstExtra: number,
	/**  What the community rules say the overflow is: a pre-selection for the card, never applied without confirmation. */
	hint?: SplitHint | null,
};

/**  Which kind of Karasu a `/Sessions` row is; ordered, because a desktop outranks a phone and that order is the rule. */
export type Platform = "mobile" | "desktop";

/**  What the screen needs to know about where it runs; tray presence stays with `get_close_to_tray`, one source. */
export type PlatformInfo = {
	/**  "windows" | "linux" | "android", whatever `std::env::consts::OS` says. */
	os: string,
	/**  Running from an AppImage, the only Linux layout the updater can replace and portable mode can write beside. */
	appImage: boolean,
};

export type PortableStatus = {
	portable: boolean,
	/**  Absolute path where the database currently lives. */
	dir: string,
	/**  A database in the folder this switch would move away from; `None` when that folder holds nothing. */
	other: DatabaseInfo | null,
};

/**  One queued edit, described rather than replayed; the payload itself never crosses to the frontend. */
export type QueuedEdit = {
	id: number,
	/**  `"save"` or `"delete"`. */
	kind: string,
	/**  The media id for a save, the list-entry id for a delete, `None` when the payload does not parse but still a row. */
	subject: number | null,
	/**  The fields this edit changes, for the row's summary line. */
	fields: string[],
	queuedAt: number,
};

/**  What the sync panel shows about the limiter; local state only, so reading it costs no request. */
export type RateSnapshot = {
	/**  `None` until a response header has been seen this session. */
	remaining: number | null,
	limit: number | null,
	observedAgoMs: number | null,
	/**  Independent of `remaining`, never derived from it: a 429 may omit the header, and this is the signal to branch on. */
	throttledForMs: number | null,
	throttleKind: string | null,
};

/**  One row of the panel's traffic list. */
export type RequestLogEntry = {
	/**  Monotonic within a session, so the panel has a stable React key. */
	seq: number,
	/**  The caller's name for itself, so the panel can say which screen or pass spent the budget. */
	source: string,
	/**  The root field asked for. Never the variables — see `operation_name`. */
	operation: string,
	startedAgoMs: number,
	durationMs: number,
	/**  How long this request waited on the client's own pacing; separate from `durationMs`, since the fixes differ. */
	pacedMs: number,
	status: number | null,
	remainingAfter: number | null,
	/**  `"ok" | "throttled" | "error"`. */
	outcome: string,
};

export type ScanSummary = ScanSummary_Serialize | ScanSummary_Deserialize;

export type ScanSummary_Deserialize = {
	entries: LibraryEntry_Deserialize[],
	/**  Total video files seen (matched or not). */
	files: number,
	matched: number,
};

export type ScanSummary_Serialize = {
	entries: LibraryEntry_Serialize[],
	/**  Total video files seen (matched or not). */
	files: number,
	matched: number,
};

export type ScrobbleSettings = {
	enabled: boolean,
	/**  true = require confirmation in the UI before updating */
	confirm: boolean,
	/**  threshold in minutes; 0 = automatic (2/3 of the episode length) */
	delayMin: number,
	/**  Whether an episode-gap block lifts itself after the grace period; off by default, since the default is asking. */
	gapAuto: boolean,
};

/**  `/System/Info/Public`, the parts the app uses. */
export type ServerInfo = {
	name: string,
	id: string,
	version: string,
};

/**  One row of the Test-connection diagnostic. */
export type SessionSummary = {
	user: string,
	device: string,
	client: string,
	deviceId: string,
	/**  What that session is playing, or `None` when it is idle. */
	playing: string | null,
	/**  Whether the configured user/device filter accepts this session. */
	matched: boolean,
	/**  Set when the row is a Karasu — this one included — with its platform. */
	karasu: Platform | null,
	/**  Seconds between this row's last activity and this instance's own row, on the server clock; what `yield_to` judges by. */
	activeAgoSec: number | null,
};

export type SplitHint = {
	mediaId: number,
	dstStart: number,
};

export type StaleSettings = {
	enabled: boolean,
	months: number,
};

export type Suggested = {
	mediaId: number,
	score: number,
};

/**  Everything the sync panel renders, at the cost of no AniList request, which is what makes polling it acceptable. */
export type SyncStatus = {
	/**  Signed in to AniList; false in local mode, where an empty queue is not the same statement. */
	connected: boolean,
	draining: boolean,
	queued: QueuedEdit[],
	rate: RateSnapshot,
	/**  Recent AniList traffic, newest first, so the panel can show what moved the headroom. */
	recent: RequestLogEntry[],
	/**  Requests per source since the app started, so the panel can say who is spending the budget. */
	traffic: TrafficSnapshot,
};

/**  The parse a correction is keyed on: what the release name said it was. */
export type TitleKey = {
	title: string,
	season: number,
	/**  Whether this parse carries a correction; always computed by `reindex`, since nothing deserializes a `TitleKey`. */
	manual?: boolean,
};

/**  What the panel and the diagnostics report see of the tallies. */
export type TrafficSnapshot = {
	/**  Requests per source since the app started, alphabetical. */
	sources: TrafficSource[],
	/**  HTTP 429 answers since the app started. */
	throttled: number,
	remaining: number | null,
	limit: number | null,
};

export type TrafficSource = {
	source: string,
	total: number,
};

/**  Files that parsed to a title the matcher could not place. */
export type UnmatchedGroup = {
	title: string,
	season: number,
	files: LibraryFile[],
	/**  What AniList thinks this is, unconfirmed: the screen shows it greyed and the user decides. */
	suggestion: Suggested | null,
};

export type UpdateInfo = {
	/**  The running app version. */
	current: string,
	/**  Latest published release tag (without a leading "v"), if any. */
	latest: string | null,
	/**  Release page URL. */
	url: string | null,
	isNewer: boolean,
	/**  The selected channel has no release to compare against, which is not the same as "up to date". */
	channelEmpty: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

